title: Timothy Escopete
url: "https://www.timothyae.com"
baseurl: ""

markdown: kramdown

tracking_id: #

sass:
  style: compressed
  sass_dir: _sass

excerpt_separator: "\n\n"
permalink: pretty

collections:
  pages:
    output: true

disqus:
  handle: timhtheos
  url:
    old: timothyae.com
    new: timothy.sh

# Alias generator.
safe: false

# Make all future posts unpublished.
future: false
