title: Timothy Escopete
url: "https://timothy.sh"
baseurl: ""

markdown: kramdown

tracking_id: #

sass:
  style: compressed
  sass_dir: _sass

excerpt_separator: "\n\n"
permalink: pretty

collections:
  pages:
    output: true

disqus:
  handle: timhtheos
  url:
    old:  timothy.sh
    new:  timothy.sh

# Alias generator.
safe: false

# Make all future posts unpublished.
future: false

gems:
  - jekyll-archives

jekyll-archives:
  enabled: all
  layouts:
    year: archive-year
    month: archive-month
    day: archive-day
    tag: category
    category: category
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

yt:
  dimension:
    width: 850
    height: 477
  settings:
    rel: 0
    autoplay: 1
    controls: 0
    showinfo: 0
    start: 0
    end: 0
    loop: 1
    modestbranding: 1
    fs: 0
    autohide: 0
    mute: 0
    enablejsapi: 1
  captions:
    title: 
    subtitle: 
  # ids are youtube ids and can declared as:
  # - jsB-PwkhXV8
  # or:
  # -
  #   id: jsB-PwkhXV8
  ids:
    # fall into you
    # - f1x16SkHizQ
    # am2pm
    - 
      id: jsB-PwkhXV8
    # the hurt
    # - 
      # id: ybXfLo_OBOg
    # concrete angel
    # -
      # id: 0dFz10R529g
    #   autoplay: 1
    #   controls: 1
    #   showinfo: 1
    # black hole
    # - 
    #   id: WPVv-Jjb0wQ
    #   dimension:
    #     width: 850
    #     height: 358
